### ISSUE TITLE
`playTrackInFolder()` is misleading

### ISSUE THREAD

**Issue by scottchiefbaker** [bluejunimo/YX5300_ESP32#1]
Minor gripe, but `playTrackInFolder(X, Y);` is named slightly confusing. When I read that (in English) I see:

"Play track #X that is in folder #Y", but it's really the opposite. I know I could RTFM, but the function name could also be more helpful.

**Comment by scottchiefbaker** [comment]
Sorry that came off as complainy... 

This library is great! It got me up and working in no time. It's well designed and simple. Time permitting I'll submit a couple  additional examples.

What ESP32s have you tested with? I started on a C3 (SERIAL1 vs SERIAL2) and was having issues where the serial communication wasn't reliable. Switching to a vanilla ESP32 solved my problems.

**Comment by bluejunimo** [comment]
Thanks for all your feedback on the library. It's my first time making one of these and I'm a novice programming, so the feedback is very much appreciated.

I've only used the library on these MakePico ESP-32 boards: https://www.tinytronics.nl/en/development-boards/microcontroller-boards/with-wi-fi/makepico-esp32-d0wdq6-development-board-with-wi-fi-and-bluetooth

I think they are C3 but I'm not sure.

**Comment by scottchiefbaker** [comment]
Doing some research it looks like the ESP32 Dev boards have 4x UARTS (Serial, Serial1, Serial2, Serial3). The ESP32 S2/C3 only have 2x UARTS (Serial, and Serial1).

The reason I mention this is because one of your examples uses Serial2 which won't exist on S2/C3 boards. Might be a good idea to change that example to say `Serial1`. That's how I fixed it to work with my C3.

I was testing with a C3 and I had some issues with certain ports. I need to document them and we can put them in the README. 

The board you link is vanilla ESP32.

**Comment by bluejunimo** [comment]
> Might be a good idea to change that example to say `Serial1`. That's how I fixed it to work with my C3.

I will add those changes in the next update
